### ISSUE TITLE
如何将依赖模块合并到一个主模块文件？

### ISSUE THREAD

**Issue by inickel** [modulex/modulex#2]
- src
  - core（kissy）
    - node
  - module
    - index

codes of index 

``` javascript
define(function(require,exports,module){
  require('node');
});
```

在合并的时候将core(kissy)里面的node模块合并到index模块文件；

目前我想到的思路是在node里面使用modulex-nodejs加载器去加载，在模块信息里面找到相对应的模块依赖信息和本地路径（找到依赖的map和本地文件就可以继续接下来的文件代码的转换和合并了）；
但现在遇到一个问题，因为执行环节为nodejs，某些依赖于运行环境（如window）的判定的时候，就会出现问题（报错feature模块对window对象的引用）；

我们在使用modulex+kissy内核的时候，没有构建自己的静态服务以支持modulex的combine；所以想要在上线前压缩合并主模块文件，现主要问题如下：
1：思路是否可行，或者是否有更好的思路
2：如果以上思路可行，如何避免在nodejs环境下的(window对象)引用的报错，（是否有模拟浏览器执行的方案）
ths

**Comment by yiminghe** [comment]
kissy core 里面很多条件加载，没办法离线打包的
